#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config shadowless_monocle   true
bspc config presel_feedback_color \#d5c4a1

bspc rule -a Firefox desktop=^2
bspc rule -a Spotify desktop=^4

bspc config focus_follows_pointer true

bspc config normal_border_color \#3c3836
bspc config focused_border_color \d5c4a1

# programs for initialization
nitrogen --restore &
picom & 
~/.config/polybar/launch.sh --forest
dunst
flameshot
